apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: end-to-end-rag-pipeline-svc-api
  description: APIs of end-to-end-rag-pipeline-svc-api
spec:
  type: openapi
  lifecycle: production
  owner: development
  system: development
  definition:
    $text: ./src/swagger.json